"""#87 配置漂移检测（noul + score 变式「未审差异数」）。两份配置，注入 0–3 处行为差异与若干装饰差异。

同一状态两道题（test + measure）同层一次调用；p87 报 noul，p87s 报 score。
"""

from __future__ import annotations

import random

import foundation.jv as jv

from ._common import (Probe, Result, Sample, bare_ask, bare_state, exit_to_result, parse_noul, parse_score, q_noul, q_score, register)

_BASE = [("[server]", None), ("host", "api.internal"), ("port", "8080"), ("timeout", "30"), ("workers", "4"),
         ("[features]", None), ("beta_search", "false"), ("audit_log", "true"), ("[retry]", None), ("max_attempts", "3"),
         ("backoff", "2.0")]
_BEHAV = [("timeout", "5"), ("workers", "16"), ("beta_search", "true"), ("audit_log", "false"), ("max_attempts", "1"),
          ("port", "9090"), ("host", "api-canary.internal"), ("backoff", "0.5")]
_COSMETIC = ["comment", "reorder", "quote", "space"]


def _render(pairs, cosmetic: list[str], rnd: random.Random) -> str:
    lines = []
    for k, v in pairs:
        if v is None:
            lines.append(k)
            continue
        if "quote" in cosmetic and k in ("host",):
            v = f'"{v}"'
        if "space" in cosmetic:
            lines.append(f"{k} = {v}")
        else:
            lines.append(f"{k}={v}")
    if "comment" in cosmetic:
        lines.insert(1, "# generated by deploy tool")
        lines.append("# end")
    if "reorder" in cosmetic:
        i = lines.index("[features]")
        lines[i + 1], lines[i + 2] = lines[i + 2], lines[i + 1]
    return "\n".join(lines)


def make_samples(n: int = 24, seed: int = 0) -> list[Sample]:
    rnd = random.Random(seed)
    out = []
    for i in range(n):
        k = [0, 1, 0, 2, 0, 3][i % 6]                          # 行为差异数：一半 0（负例），其余 1/2/3
        a = _render(_BASE, [], rnd)
        pairs = list(_BASE)
        chosen = rnd.sample(_BEHAV, k)
        for key, val in chosen:
            pairs = [(kk, val if kk == key else vv) for kk, vv in pairs]
        b = _render(pairs, rnd.sample(_COSMETIC, rnd.randint(1, 3)), rnd)
        level = 0 if k == 0 else (1 if k <= 2 else 2)
        out.append(Sample(id=f"p87-{i:02d}", truth=k > 0, mats={"a": a, "b": b}, meta={"k": k, "level": level}))
    return out


有漂移 = jv.test("两份配置之间存在会改变程序运行行为的差异吗（忽略注释、顺序、引号、空格）？", calib=jv.calib("probe87.有漂移"))
几处 = jv.measure("两份配置之间有几处会改变程序行为的差异？", scale=("没有", "一到两处", "三处以上"), calib=jv.calib("probe87.几处"))


@jv.program(budget=jv.Budget(calls=40, cost=0.05, layers=1))
def 检测(pairs, keys):
    rs = jv.judge([jv.state(on=(a, b)) for a, b in pairs], 有漂移, 几处)        # 同状态两题 → 一次调用
    ex1, ex2 = jv.cut([r[0] for r in rs]), jv.cut([r[1] for r in rs])
    r1 = [exit_to_result(sid, t1, e, "noul") for (sid, t1, t2), e in zip(keys, ex1)]
    r2 = [exit_to_result(sid, t2, e, "score") for (sid, t1, t2), e in zip(keys, ex2)]
    return r1, r2


def _run(samples):
    return 检测([(jv.lit(s.mats["a"]), jv.lit(s.mats["b"])) for s in samples], [(s.id, s.truth, s.meta["level"]) for s in samples])


def builder(samples, rt):
    return _run(samples)[0]


def builder_score(samples, rt):
    return _run(samples)[1]


def bare(samples, client, tally):
    out = []
    for s in samples:
        a = bare_ask(client, bare_state(on=(s.mats["a"], s.mats["b"])), {"q0": q_noul(有漂移.text), "q1": q_score(几处.text, 几处.scale)}, tally)
        pred, p = parse_noul(a["q0"])
        out.append(Result(s.id, s.truth, pred, p, "bare"))
    return out


def bare_score(samples, client, tally):
    out = []
    for s in samples:
        a = bare_ask(client, bare_state(on=(s.mats["a"], s.mats["b"])), {"q0": q_noul(有漂移.text), "q1": q_score(几处.text, 几处.scale)}, tally)
        lvl, p = parse_score(a["q1"])
        out.append(Result(s.id, s.meta["level"], lvl, p, "bare"))
    return out


def _difflines(s: Sample) -> int:
    import difflib
    d = [l for l in difflib.unified_diff(s.mats["a"].splitlines(), s.mats["b"].splitlines(), lineterm="", n=0)
         if (l.startswith("+") or l.startswith("-")) and not l.startswith(("+++", "---"))]
    return len(d)


def baseline(samples):
    """启发式：原始 diff 行数 > 0 即漂移（装饰差异也算，天然偏高）。"""
    return [Result(s.id, s.truth, _difflines(s) > 0, min(1.0, _difflines(s) / 6), "difflines") for s in samples]


def baseline_score(samples):
    out = []
    for s in samples:
        n = _difflines(s) // 2
        out.append(Result(s.id, s.meta["level"], 0 if n == 0 else (1 if n <= 2 else 2), None, "difflines"))
    return out


register(Probe("p87", "配置漂移检测", "noul", make_samples, builder, bare, baseline, note="noul + score 同状态一次调用"))
register(Probe("p87s", "配置漂移：未审差异数（score 变式）", "score", make_samples, builder_score, bare_score, baseline_score))
